"""empty message

Revision ID: ab8eee972d95
Revises: 3ee26ae7ac1f
Create Date: 2019-11-05 15:20:36.064607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab8eee972d95'
down_revision = '3ee26ae7ac1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_first_name', table_name='user')
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.drop_index('ix_user_second_name', table_name='user')
    op.create_index(op.f('ix_user_second_name'), 'user', ['second_name'], unique=False)
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_index(op.f('ix_user_second_name'), table_name='user')
    op.create_index('ix_user_second_name', 'user', ['second_name'], unique=1)
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.create_index('ix_user_first_name', 'user', ['first_name'], unique=1)
    # ### end Alembic commands ###
